[[redirects]]
  force = true
  from = "/clients"
  status = 200
  to = "https://specialprojectapplication.herokuapp.com/clients"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "https://specialprojectapplication.herokuapp.com/splat:"

[[redirects]]
 from = '/*'
 to = '/index.html'
 status = 200


